config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, reject_if: :all_blank

  validates :title, :content, presence: true
  validates :title, uniqueness: true
end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true, with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @tag = Tag.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @tag = Tag.new
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :tags, tag_ids: [])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      render @tag
    else
      render partial: 'error', locals: {tag: @tag}, status: :bad_request
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stimulusapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Stimulusapp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Posts", posts_path, class: "nav-link", method: :get %>
          </li>
          <li class="nav-item active">
            <%= link_to "Tags", tags_path, class: "nav-link", method: :get %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_errors.html.erb
<% if local_assigns.has_key? :errors %>
  <% if errors.any? %>
    <div class="bg-red-lightest border-l-4 border-red text-red-dark p-4 mb-4 text-left">
      <% errors.each do |msg| %>
        <p class="mb-0"><%= msg %></p>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "erro", plural: "erros") %> impediram esse post de ser salvo:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title %>
  </div>

  <div class="form-group">
    <%= f.input :content %>
  </div>

  <div class="form-group">
    <div data-tags-target="tagList">
      <%= f.label :tag_ids, label: 'Tags para o post:' %> <button class="btn btn-primary" id="menu-toggle">Criar tag</button><br>
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, include_hidden: false do |box| %>
        <%= box.check_box %>
        <%= box.label %>
        <br>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary" %>
    <%= link_to 'Back', posts_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/posts/_tag_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>
  <div class="form-group">
    <%= form.input :name %>
    <small><%= link_to "Remove", "#", data: { action: "click->tags#remove_tag" } %></small>
  </div>
<% end %>

app/views/posts/_tag_form.html.erb
<%= form_with model: tag, data: { action: "ajax:success->tags#createSuccess ajax:error->tags#createError" } do |t| %>
  <div data-tags-target="tagErrors"></div>
  <div class="ml-2 mt-2">
    <h4 class="text-center">Criar tag</h4>
    <%= t.label :name, "Nome da Tag:", class: "mt-2" %>
    <%= t.text_field :name, data: { target: 'tags.tagName' } %>
    <%= t.submit style: 'display: block', class: "btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="row">
    <div class="col-sm">
      <h1>Posts</h1>
    </div>
    <div class="col-sm text-right mt-2">
      <%= link_to new_post_path, class: 'btn btn-primary', method: :get do %>
        Criar Post
      <% end %>
    </div>
</div>

<table class="table table-bordered table-hover">
  <thead> 
    <tr>
      <th scope="col">#</th>
      <th scope="col">Título</th>
      <th scope="col">Conteúdo</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Mostrar', post, class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div data-controller="tags">
  <div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="list-group list-group-flush">
        <%= render 'tag_form', tag: @tag %>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="container-fluid">
        <h1 class="mt-4">Novo post</h1>
        <%= render 'form', post: @post %>
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>
</div>

app/views/posts/show.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-danger' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Posts
  <% end %>
  <%= link_to edit_post_path(@post), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show post</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @post.title %></dd>

  <dt>Content:</dt>
  <dd><%= @post.content %></dd>

  <% if @post.tags.any? %>
    <dt>Tags:</dt>
    <% @post.tags.each do |tags| %>
      <dd><%= tags.name %></dd>
    <% end %>
  <% end %>
</dl>

app/views/tags/_error.html.erb
<% if tag.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if tag.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', tag, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if tag.persisted? %>
      <%= link_to "Cancel", tag, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", tags_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
  <div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Start Bootstrap </div>
      <div class="list-group list-group-flush">
        <a href="#" class="list-group-item list-group-item-action bg-light">Dashboard</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Shortcuts</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Overview</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Events</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Profile</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Status</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
        <h1 class="mt-4">Simple Sidebar</h1>
        <p>The starting state of the menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will change.</p>
        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>. The top navbar is optional, and just for demonstration. Just create an element with the <code>#menu-toggle</code> ID which will toggle the menu when clicked.</p>
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>

app/views/tags/new.html.erb
<h1>Nova tag</h1>

<%= render 'form', tag: @tag %>

app/views/tags/show.html.erb
<div class="page-header">
  <%= link_to tags_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Tags
  <% end %>
  <%= link_to edit_tag_path(@tag), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show tag</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @tag.name %></dd>

</dl>